#!/usr/bin/env bash
set -euo pipefail
VER="${1:-1.3.3}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/packaging/dist"
STAGE="$ROOT/packaging/.stage"
rm -rf "$DIST" "$STAGE"
mkdir -p "$DIST" "$STAGE/DEBIAN"
install -d "$STAGE/usr/local/sbin" "$STAGE/etc/systemd/system" "$STAGE/etc/pg-backup.d" "$STAGE/etc/pg-backup.hooks/pre.d" "$STAGE/etc/pg-backup.hooks/post-db.d" "$STAGE/etc/pg-backup.hooks/post.d" "$STAGE/usr/share/doc/pg-backup-toolkit" "$STAGE/var/log/pg-backup" "$STAGE/backups/postgres"
install -m 0755 "$ROOT/scripts/"* "$STAGE/usr/local/sbin/"
install -m 0644 "$ROOT/systemd/"* "$STAGE/etc/systemd/system/"
install -m 0644 "$ROOT/config/pg-backup.conf" "$STAGE/etc/pg-backup.conf"
install -m 0644 "$ROOT/config/nightly.conf"  "$STAGE/etc/pg-backup.d/nightly.conf"
install -m 0644 "$ROOT/config/hourly.conf"   "$STAGE/etc/pg-backup.d/hourly.conf"
install -m 0644 "$ROOT/config/weekend.conf"  "$STAGE/etc/pg-backup.d/weekend.conf"
install -m 0644 "$ROOT/docs/guide.html" "$STAGE/usr/share/doc/pg-backup-toolkit/guide.html"
sed "s/^Version:.*/Version: ${VER}/" "$ROOT/packaging/control" > "$STAGE/DEBIAN/control"
install -m 0755 "$ROOT/packaging/postinst" "$STAGE/DEBIAN/postinst"
install -m 0755 "$ROOT/packaging/prerm"    "$STAGE/DEBIAN/prerm"
install -m 0755 "$ROOT/packaging/postrm"   "$STAGE/DEBIAN/postrm"
install -m 0644 "$ROOT/packaging/conffiles" "$STAGE/DEBIAN/conffiles"
find "$STAGE/usr/local/sbin" -type f -exec chmod 0755 {} +
chmod 0644 "$STAGE/usr/share/doc/pg-backup-toolkit/guide.html"
fakeroot dpkg-deb --build "$STAGE" "$DIST/pg-backup-toolkit_${VER}_all.deb"
echo "Built: $DIST/pg-backup-toolkit_${VER}_all.deb"
