name: build-deb
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build .deb
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg-dev
          cd packaging
          bash mkdeb.sh ${GITHUB_REF_NAME#v} || bash mkdeb.sh 1.3.3
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup-toolkit
          path: dist/*.deb
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pg-backup-toolkit
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
